### ISSUE TITLE
tlmgr package repository not configured to the correct version?

### ISSUE THREAD

**Issue by yves-chevallier** [kjarosh/latex-docker#14]
When I use the `2022.2` the value of the `tlmgr option repository` is the refault one (2024): 

```bash
$ docker run -it -v $(pwd):/workspace -w /workspace kjarosh/latex:2022.2-basic
Digest: sha256:a469ff83692abda0901739e641ebf38552770b66361c8f4cf473a08bea0d575e

/workspace # tlmgr option repository
Default package repository (repository): https://texlive.info/CTAN/systems/texlive/tlnet
```

So I decided to update the repository, but it seems the installed version is always the latest: 

```
$ docker run -it -v $(pwd):/workspace -w /workspace kjarosh/latex:2023.3-basic  
Digest: sha256:880edbeb980c8eed46291a3be39020adc507d66d9028f4079ea683b7d5ac11c7
Status: Downloaded newer image for kjarosh/latex:2023.3-basic
/workspace # tlmgr option repository http://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2023/tlnet-final/
tlmgr: setting default package repository to http://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2023/tlnet-final/
tlmgr: updating /opt/texlive/tlpkg/texlive.tlpdb

/workspace # tlmgr install minted
tlmgr: The TeX Live versions supported by the repository
http://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2023/tlnet-final/
  (2016--2023)
do not include the version of the local installation
  (2024).
```

Can someone explain to me what I missed?

**Comment by kjarosh** [comment]
Thank you for your report! Indeed, it seems that something's wrong with the newest images. I suspect development images have been mistakenly published as older final versions. I will investigate and fix this issue soon.

In the meantime you can use `kjarosh/latex:2022.1-full` which should work properly. Sorry for the trouble!

**Comment by kjarosh** [comment]
The newly released version `2022.3` should be fixed, along with the newest versions of editions `2019`–`2024`. I am working on fixing versions older than 2019.

I'll also update the broken versions so that people won't get confused.

**Comment by kjarosh** [comment]
Okay, fixed versions `2018`–`2024`, I had some issues with versions older than 2018, so I removed references to them for now.

Let me know if everything works now

**Comment by kjarosh** [comment]
I'm gonna close it for now, let me know if something still doesn't work properly
